### ISSUE TITLE
Bug: Tag pages missing pagination

### ISSUE THREAD

**Issue by dschier-wtd** [TryGhost/Source#10]
Hey all, thanks for the awesome theme.

I just switched to it and it looks pretty nice.

Unfortunately, I discovered that tag pages are showing 16 articles, only, and have no way to show older articles. Therefore, people cannot see more than 16 articles per tag. You can find an example here: https://blog.while-true-do.io/tag/automation/

I am using source 1.0.0 on Ghost 5.67.0.

I hope this can be hammered out quickly. In case I can support you with the same, please don't hesitate to reach out/ping me.

**Comment by minimaluminium** [comment]
Hey @dschier-wtd, thanks for the report!

The issue has just been fixed in `1.0.1`.

**Comment by dschier-wtd** [comment]
works like a charm. thanks a lot!
