### ISSUE TITLE
Navigation scroll issue on mobile

### ISSUE THREAD

**Issue by lorumic** [TryGhost/Source#12]
When scrolling the fixed navigation element on mobile, the scroll event is propagated to the rest of the page once the bottom/top is reached.

Ideally, this should not happen. The page below should retain the position that it had when the navigation menu was opened, and it should not be accidentally scrolled as a result of the scrolling on the navigation.

See the problem in action:

![Peek 2023-10-16 15-56](https://github.com/TryGhost/Source/assets/56583786/3375456d-2a61-4565-b68a-157764c9c9f7)

I was trying to fix this myself, but there are multiple ways to to tackle this problem, so I thought it would be better to open an issue first, to discuss which would be the preferable way to fix it.

**Comment by minimaluminium** [comment]
Thanks for your report! The issue has been fixed in https://github.com/TryGhost/Source/commit/c06094436434c257043e096b1a94e46fae32d465
