### ISSUE TITLE
New issues after #10

### ISSUE THREAD

**Issue by dschier-wtd** [TryGhost/Source#14]
With the fix of #10 2 new issues were introduced.

First, the new "endless scrolling" prevents that the footer can be seen properly. This might be an oversight, but the footer is no longer visible and therefore the secondary links are unavailable.

Second, when scrolling below the initial content (the moment when endless scrolling starts) the same content will be displayed again. Therefore, there is a lot of duplication when scrolling down.

**Comment by minimaluminium** [comment]
Hey @dschier-wtd, this has been fixed in 1.0.2? Could you install the version manually and see if it works?

**Comment by dschier-wtd** [comment]
@minimaluminium , I gave it a try:

- landing page works as intended (See all leads to endless scroll)
- Tag pages are endless scrolling enabled, too

So far, this seems to be a nice implementation and works very well.

Thank you, for the effort!

**Comment by minimaluminium** [comment]
Thanks a lot for the feedbacks and tests!
