### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by vinzent** [TryGhost/Source#15]
Given the portal is getting translations now and this is the new default theme: is Source accepting translations pull-requests? I'd love to see german translation and I'd like to work on it.

**Comment by vinzent** [comment]
https://github.com/TryGhost/Source/pull/18

**Comment by vinzent** [comment]
There are 2 PR's for translations now: 

https://github.com/TryGhost/Source/pull/31
https://github.com/TryGhost/Source/pull/18

**Comment by vinzent** [comment]
I asked the support if they go to support translations. They answered they won't currently support translations. But they are planning to some time in the future. But no ETA yet. Would be nice if they would give feedback to contributors here too.

**Comment by minimaluminium** [comment]
You're very welcome to translate the theme or release your own translated themes! We're not ready to include translations by default in the theme at the moment.
