### ISSUE TITLE
The "Latest" header on the homepage

### ISSUE THREAD

**Issue by leslietech** [TryGhost/Source#16]
I notice that my 5th newest blog article and older are listed under the "Latest" section below the "Subscribe" section on the home page. I am using the "Highlight" header style. I am running Ghost v5.70.1, and Source v1.1.0.

![image](https://github.com/TryGhost/Source/assets/49253776/9e5d71da-ce52-4369-b1b8-21d1f1cef6e2)

Is this "Latest" header referring to the items below it, or above it?

**Comment by minimaluminium** [comment]
The Highlight header shows the first 4 posts (1 on the left, 3 in the middle). Then the Latest section displays the posts starting from fifth which is intended.
