### ISSUE TITLE
MD Tables have problem

### ISSUE THREAD

**Issue by vincentzzzzzz** [TryGhost/Source#17]
![image](https://github.com/TryGhost/Source/assets/53964070/4178cb7a-d9f3-408e-9be4-c702ed5c36cd)
![image](https://github.com/TryGhost/Source/assets/53964070/548bba9e-d7a5-42e4-83f6-cec938d17aaf)

**Comment by vincentzzzzzz** [comment]
Markdown tables have problem.

**Comment by minimaluminium** [comment]
Thanks for your report. The issue has been fixed in https://github.com/TryGhost/Source/commit/ebc479215410acc46ae00b90c0f0b117da616a7d - should be out with the next release.
