### ISSUE TITLE
Technocolor site

### ISSUE THREAD

**Issue by hawkkiller** [TryGhost/Source#25]
Hi there! Thanks for this amazing theme.

I wonder if there is a code for https://source-newsletter.ghost.io/ to take a look at.

**Comment by minimaluminium** [comment]
Hey @hawkkiller, we haven't used any code injection for this. All our official Source theme demos have been created with the included theme settings. You can play with them in the Design settings on your dashboard.

**Comment by hawkkiller** [comment]
@minimaluminium Thanks for your response! I still have a few questions:
- How did you manage to create a [/page/2](https://source-newsletter.ghost.io/page/2/) with all the issues?
- How did you put the subscribe button on the homepage? I can currently achieve a search button using the Search header template.

thanks for your help.
