### ISSUE TITLE
Picture not shown?

### ISSUE THREAD

**Issue by EchoBilisim** [TryGhost/Source#32]
Hello, there seems to be an issue with one of the contents on the homepage. I noticed that an image is not appearing in the designated section. I checked the demo site, and the same problem persists there as well. I attached a screenshot of the selected area where the image should be, but it's not visible. Is this an error on my part or is it a known issue?

![Ekran görüntüsü 2023-12-01 234709](https://github.com/TryGhost/Source/assets/17055352/d6c21bf6-68e8-4faf-83b6-52b6e8c49fad)

**Comment by minimaluminium** [comment]
This is intentional by design to hide the image of the last post in the middle column to keep the balance of the overall section. If you still want to show the image of the post, use this CSS as code injection.

```html
<style>
    .gh-header.is-highlight .gh-header-middle .gh-card:last-child .gh-card-image {
        display: block;
    }
</style>
```

**Comment by EchoBilisim** [comment]
> This is intentional by design to hide the image of the last post in the middle column to keep the balance of the overall section. If you still want to show the image of the post, use this CSS as code injection.
> 
> ```
> <style>
>     .gh-header.is-highlight .gh-header-middle .gh-card:last-child .gh-card-image {
>         display: block;
>     }
> </style>
> ```

I understand. I tested it, and yes, as you mentioned, it looks better in its original form. I have decided to use the original version. Thank you very much for your response.
