### ISSUE TITLE
Improve accessibility rating

### ISSUE THREAD

**Issue by burgyman** [TryGhost/Source#37]
Hi,

Not really an issue but since I'm not a developer and don't know how to create/submit PRs, I'm dropping it here.

I've made a couple of changes to improve the accessibility rating on [Google PageSpeed Insights](https://pagespeed.web.dev/) that maybe you could look into implementing:

added title="Subscribe" aria-label="Subscribe" in email-subscription.hbs
`<button class="gh-button" type="submit" title="Subscribe" aria-label="Subscribe">`

added title="Menu" aria-label="Menu" in navigation.hbs
`<button class="gh-burger gh-icon-button" title="Menu" aria-label="Menu">`

These basically improved the accessibility rating for my website homepage to 100%!
I will look to do the same in other files that use `<button>` tags...
Wanted to contribute to Ghost and improve even more the amazing Source theme :)

Best,
Pedro

**Comment by minimaluminium** [comment]
Hey @burgyman, thanks for the feedbacks!

Your suggestions have been implemented in https://github.com/TryGhost/Source/commit/dc3e6cb5395efbb52e3463f79345b13543d47e2a, should be out with the next release.
