### ISSUE TITLE
Pagination missing on front page

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Source#40]
The Source theme seems to be missing any use of the {{pagination}} helper on the front page.  Because it's making a {{get}} request, it's not possible to navigate to /page/2 and beyond.

**Comment by Sahillather002** [comment]
pls assign

**Comment by raad-altaie** [comment]
Is this ever going to be fixed?

**Comment by minimaluminium** [comment]
Fixed in [1.3.2](https://github.com/TryGhost/Source/commit/61a511b229f3005856dadf625a24d697d5b07986)

**Comment by minimaluminium** [comment]
Lack of pagination on the frontend is by design. Source and a few other official themes (Headline, Episode, Digest, Bulletin) uses `/page/2` as the archive page to list all posts.
