### ISSUE TITLE
See All at the bottom of the Home Page is not visible

### ISSUE THREAD

**Issue by EchoBilisim** [TryGhost/Source#56]
Hello, I updated the theme and ghost to the latest version, but for your information, the See All option at the bottom of the home page has disappeared.

![Ekran görüntüsü 2024-07-19 161746](https://github.com/user-attachments/assets/75898b7e-1a98-4709-89a1-89a215eae423)

**Comment by minimaluminium** [comment]
Hey @EchoBilisim, do you have a link to your site where we can test?

**Comment by minimaluminium** [comment]
The link should appear when the site has more than 12 posts AND the post list has 12 posts assuming you haven't changed `posts_per_page` or the number of posts in the post list.

If you changed, you should override the CSS in code injection:

```
<style>
    .home-template .gh-feed:has(> :nth-child(12):last-child) ~ .gh-more {
        display: block;
    }
</style>
```

Replace 12 with the number of posts you show in the post list. For example:

```
.home-template .gh-feed:has(> :nth-child(15):last-child) ~ .gh-more
```

**Comment by EchoBilisim** [comment]
> Sitede 12'den fazla mesaj varsa ve mesaj listesinde 12 mesaj varsa, `posts_per_page`mesaj listesindeki mesaj sayısını değiştirmediğinizi varsayarak bağlantı görünmelidir.
> 
> Eğer değiştirdiyseniz, kod enjeksiyonundaki CSS'yi geçersiz kılmalısınız:
> 
> ```
> <style>
>     .home-template .gh-feed:has(> :nth-child(12):last-child) ~ .gh-more {
>         display: block;
>     }
> </style>
> ```
> 
> 12'yi gönderi listesinde gösterdiğiniz gönderi sayısıyla değiştirin. Örneğin:
> 
> ```
> .home-template .gh-feed:has(> :nth-child(15):last-child) ~ .gh-more
> ```

Yes, the topics disappeared from the view count. I reverted the view count to its original state, and they reappeared. When I change it again, they disappear. I added the code you provided, but nothing changed. Below is the view count I am using. I adjusted the code you gave me, but it still doesn't show.

`{{#get "posts" include="authors" limit="28"}}`

**Comment by minimaluminium** [comment]
If you've changed the limit to 28, you should replace `15` with `28`. Or simply make the link visible all the time with:
```
<style>
    .home-template .gh-more {
        display: block !important;
    }
</style>
```

**Comment by EchoBilisim** [comment]
> If you've changed the limit to 28, you should replace `15` with `28`. Or simply make the link visible all the time with:
> 
> ```
> <style>
>     .home-template .gh-more {
>         display: block !important;
>     }
> </style>
> ```

Thank you very much
